<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="v3_ProektL.aspx.cs" Inherits="IIS.Product_26934.v3_ПроектL" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " + Constants.ListFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.ListFormHeaderCssClass %>">Проект</h2>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.ListFormControlsCssClass %>">
            <%--<asp:ImageButton ID="AuditBtn" runat="server" ImageUrl="~/App_Themes/BlueSky/Pages/EditPage/Images/audit.png" OnClick="AuditBtn_Click" AlternateText="Аудит"/>--%>
            <ac:WebObjectListView ID="WebObjectListView1" runat="server" Visible="true" />

 <%-- <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Mushrooms', 3],
          ['Onions', 1],
          ['Olives', 1],
          ['Zucchini', 1],
          ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = {'title':'How Much Pizza I Ate Last Night',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
  </body>--%>



            
<%--              <head>
                             
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
      
            <script type="text/javascript">--%>

            <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">


    //google.load('visualization', '1', { 'packages': ['piechart', 'imagepiechart', 'barchart', 'imageBarChart', 'linechart'] });

    google.charts.load('current', { 'packages': ['corechart'] });

    google.setOnLoadCallback(drawChart);

    function drawChart() {


        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
            ['Mushrooms', 3],
            ['Onions', 1],
            ['Olives', 1],
            ['Zucchini', 1],
            ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = {
            'title': 'How Much Pizza I Ate Last Night',
            'width': 400,
            'height': 300
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);

    //    var data = new google.visualization.DataTable();
    //    data.addColumn('string', 'list');
    //    data.addColumn('number', 'Tutorials Pesentage');
    //    data.addRows(5);
    //    data.setValue(0, 0, 'HTML');
    //    data.setValue(0, 1, 11);
    //    data.setValue(1, 0, 'CSS');
    //    data.setValue(1, 1, 39);
    //    data.setValue(2, 0, 'Разное');
    //    data.setValue(2, 1, 36);
    //    data.setValue(3, 0, 'Для сайта');
    //    data.setValue(3, 1, 22);
    //    data.setValue(4, 0, 'jQuery');
    //    data.setValue(4, 1, 85);
    //    data.setValue(3, 0, 'Mootools');
    //    data.setValue(3, 1, 14);
    //    data.setValue(3, 0, 'PHP');
    //    data.setValue(3, 1, 14);

    //    var chart = new google.visualization.ImagePieChart(document.getElementById('9lessonschart'));
    //    chart.draw(data, { width: 400, height: 240, is3D: true, title: 'Уроки на Ruseller.com' });

    //    var chart = new google.visualization.PieChart(document.getElementById('2'));
    //    chart.draw(data, { width: 400, height: 240, is3D: true, title: 'Уроки на Ruseller.com' });

    //    var chart = new google.visualization.BarChart(document.getElementById('3'));
    //    chart.draw(data, { width: 400, height: 240, is3D: true, title: 'Уроки на Ruseller.com' });

    //    var chart = new google.visualization.ImageBarChart(document.getElementById('4'));
    //    chart.draw(data, { width: 400, height: 240, min: 0 });

    //    var chart = new google.visualization.LineChart(document.getElementById('5'));
    //    chart.draw(data, { width: 400, height: 240, legend: 'bottom', title: 'Уроки на Ruseller.com' });
    }

  </script> 

      
  </head>

            
  <body>
            <div id='1'></div>
<div id='2'></div>
<div id='3'></div>
<div id='4'></div>
<div id='5'></div>
      
  </body>

        </div>
    </div>
</asp:Content>
