//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_26934
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// История окладов.
    /// </summary>
    // *** Start programmer edit section *** (ИсторияОкладов CustomAttributes)

    // *** End programmer edit section *** (ИсторияОкладов CustomAttributes)
    [AutoAltered()]
    [Caption("История окладов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "НачальнаяДата as \'Начальная дата\'",
            "КонечнаяДата as \'Конечная дата\'",
            "Оклад as \'Оклад\'"})]
    [View("v3_ИсторияОкладовE", new string[] {
            "НачальнаяДата as \'Начальная дата\'",
            "КонечнаяДата as \'Конечная дата\'",
            "Оклад as \'Оклад\'"})]
    public class ИсторияОкладов : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fНачальнаяДата;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fКонечнаяДата;
        
        private double fОклад;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.Product_26934.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (ИсторияОкладов CustomMembers)

        // *** End programmer edit section *** (ИсторияОкладов CustomMembers)

        
        /// <summary>
        /// НачальнаяДата.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.НачальнаяДата CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.НачальнаяДата CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime НачальнаяДата
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.НачальнаяДата Get start)

                // *** End programmer edit section *** (ИсторияОкладов.НачальнаяДата Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fНачальнаяДата;
                // *** Start programmer edit section *** (ИсторияОкладов.НачальнаяДата Get end)

                // *** End programmer edit section *** (ИсторияОкладов.НачальнаяДата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.НачальнаяДата Set start)

                // *** End programmer edit section *** (ИсторияОкладов.НачальнаяДата Set start)
                this.fНачальнаяДата = value;
                // *** Start programmer edit section *** (ИсторияОкладов.НачальнаяДата Set end)

                // *** End programmer edit section *** (ИсторияОкладов.НачальнаяДата Set end)
            }
        }
        
        /// <summary>
        /// КонечнаяДата.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.КонечнаяДата CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.КонечнаяДата CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime КонечнаяДата
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.КонечнаяДата Get start)

                // *** End programmer edit section *** (ИсторияОкладов.КонечнаяДата Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fКонечнаяДата;
                // *** Start programmer edit section *** (ИсторияОкладов.КонечнаяДата Get end)

                // *** End programmer edit section *** (ИсторияОкладов.КонечнаяДата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.КонечнаяДата Set start)

                // *** End programmer edit section *** (ИсторияОкладов.КонечнаяДата Set start)
                this.fКонечнаяДата = value;
                // *** Start programmer edit section *** (ИсторияОкладов.КонечнаяДата Set end)

                // *** End programmer edit section *** (ИсторияОкладов.КонечнаяДата Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.Оклад CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.Оклад CustomAttributes)
        public virtual double Оклад
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Оклад Get start)

                // *** End programmer edit section *** (ИсторияОкладов.Оклад Get start)
                double result = this.fОклад;
                // *** Start programmer edit section *** (ИсторияОкладов.Оклад Get end)

                // *** End programmer edit section *** (ИсторияОкладов.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Оклад Set start)

                // *** End programmer edit section *** (ИсторияОкладов.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (ИсторияОкладов.Оклад Set end)

                // *** End programmer edit section *** (ИсторияОкладов.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.CreateTime Get start)

                // *** End programmer edit section *** (ИсторияОкладов.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ИсторияОкладов.CreateTime Get end)

                // *** End programmer edit section *** (ИсторияОкладов.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.CreateTime Set start)

                // *** End programmer edit section *** (ИсторияОкладов.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ИсторияОкладов.CreateTime Set end)

                // *** End programmer edit section *** (ИсторияОкладов.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.Creator CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Creator Get start)

                // *** End programmer edit section *** (ИсторияОкладов.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ИсторияОкладов.Creator Get end)

                // *** End programmer edit section *** (ИсторияОкладов.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Creator Set start)

                // *** End programmer edit section *** (ИсторияОкладов.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ИсторияОкладов.Creator Set end)

                // *** End programmer edit section *** (ИсторияОкладов.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.EditTime CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.EditTime Get start)

                // *** End programmer edit section *** (ИсторияОкладов.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ИсторияОкладов.EditTime Get end)

                // *** End programmer edit section *** (ИсторияОкладов.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.EditTime Set start)

                // *** End programmer edit section *** (ИсторияОкладов.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ИсторияОкладов.EditTime Set end)

                // *** End programmer edit section *** (ИсторияОкладов.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.Editor CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Editor Get start)

                // *** End programmer edit section *** (ИсторияОкладов.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ИсторияОкладов.Editor Get end)

                // *** End programmer edit section *** (ИсторияОкладов.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Editor Set start)

                // *** End programmer edit section *** (ИсторияОкладов.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ИсторияОкладов.Editor Set end)

                // *** End programmer edit section *** (ИсторияОкладов.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Product_26934.Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияОкладов.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ИсторияОкладов.Сотрудник CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        public virtual IIS.Product_26934.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Сотрудник Get start)

                // *** End programmer edit section *** (ИсторияОкладов.Сотрудник Get start)
                IIS.Product_26934.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ИсторияОкладов.Сотрудник Get end)

                // *** End programmer edit section *** (ИсторияОкладов.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияОкладов.Сотрудник Set start)

                // *** End programmer edit section *** (ИсторияОкладов.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ИсторияОкладов.Сотрудник Set end)

                // *** End programmer edit section *** (ИсторияОкладов.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Product_26934.ИсторияОкладов));
                }
            }
            
            /// <summary>
            /// История окладов.
            /// </summary>
            public static ICSSoft.STORMNET.View v3_ИсторияОкладовE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v3_ИсторияОкладовE", typeof(IIS.Product_26934.ИсторияОкладов));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of ИсторияОкладов.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfИсторияОкладов CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfИсторияОкладов CustomAttributes)
    public class DetailArrayOfИсторияОкладов : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Product_26934.DetailArrayOfИсторияОкладов members)

        // *** End programmer edit section *** (IIS.Product_26934.DetailArrayOfИсторияОкладов members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ИсторияОкладов by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ИсторияОкладов.
        /// </summary>
        public DetailArrayOfИсторияОкладов(IIS.Product_26934.Сотрудник fСотрудник) : 
                base(typeof(ИсторияОкладов), ((ICSSoft.STORMNET.DataObject)(fСотрудник)))
        {
        }
        
        public IIS.Product_26934.ИсторияОкладов this[int index]
        {
            get
            {
                return ((IIS.Product_26934.ИсторияОкладов)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Product_26934.ИсторияОкладов dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
