//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_26934
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект.
    /// </summary>
    // *** Start programmer edit section *** (Проект CustomAttributes)

    // *** End programmer edit section *** (Проект CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Название as \'Название\'",
            "Заказчик as \'Заказчик\'",
            "Описание as \'Описание\'",
            "Обязанности as \'Обязанности\'",
            "Стоимость as \'Стоимость\'",
            "СрокНачала as \'Срок начала\'",
            "СрокЗавершения as \'Срок завершения\'",
            "Руководитель as \'Руководитель\'",
            "Руководитель.ФИО as \'ФИО\'"})]
    [View("v3_ПроектE", new string[] {
            "Название as \'Название\'",
            "Заказчик as \'Заказчик\'",
            "Описание as \'Описание\'",
            "Обязанности as \'Обязанности\'",
            "Стоимость as \'Стоимость\'",
            "СрокНачала as \'Срок начала\'",
            "СрокЗавершения as \'Срок завершения\'",
            "Руководитель as \'Руководитель\'",
            "Руководитель.ФИО as \'ФИО\'"})]
    [View("v3_ПроектL", new string[] {
            "Название as \'Название\'",
            "Заказчик as \'Заказчик\'",
            "Описание as \'Описание\'",
            "Обязанности as \'Обязанности\'",
            "Стоимость as \'Стоимость\'",
            "СрокНачала as \'Срок начала\'",
            "СрокЗавершения as \'Срок завершения\'",
            "Руководитель.ФИО as \'ФИО\'",
            "CreateTime as \'Создание\'",
            "Creator as \'Создатель\'",
            "EditTime as \'Редактирование\'",
            "Editor as \'Редактор\'"})]
    public class Проект : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fНазвание;
        
        private string fЗаказчик;
        
        private string fОписание;
        
        private string fОбязанности;
        
        private string fСтоимость;
        
        private System.DateTime fСрокНачала;
        
        private System.DateTime fСрокЗавершения;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.Product_26934.Сотрудник fРуководитель;
        
        // *** Start programmer edit section *** (Проект CustomMembers)

        // *** End programmer edit section *** (Проект CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Название CustomAttributes)

        // *** End programmer edit section *** (Проект.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Название Get start)

                // *** End programmer edit section *** (Проект.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Проект.Название Get end)

                // *** End programmer edit section *** (Проект.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Название Set start)

                // *** End programmer edit section *** (Проект.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Проект.Название Set end)

                // *** End programmer edit section *** (Проект.Название Set end)
            }
        }
        
        /// <summary>
        /// Заказчик.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Заказчик CustomAttributes)

        // *** End programmer edit section *** (Проект.Заказчик CustomAttributes)
        [StrLen(255)]
        public virtual string Заказчик
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Заказчик Get start)

                // *** End programmer edit section *** (Проект.Заказчик Get start)
                string result = this.fЗаказчик;
                // *** Start programmer edit section *** (Проект.Заказчик Get end)

                // *** End programmer edit section *** (Проект.Заказчик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Заказчик Set start)

                // *** End programmer edit section *** (Проект.Заказчик Set start)
                this.fЗаказчик = value;
                // *** Start programmer edit section *** (Проект.Заказчик Set end)

                // *** End programmer edit section *** (Проект.Заказчик Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Описание CustomAttributes)

        // *** End programmer edit section *** (Проект.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Описание Get start)

                // *** End programmer edit section *** (Проект.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Проект.Описание Get end)

                // *** End programmer edit section *** (Проект.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Описание Set start)

                // *** End programmer edit section *** (Проект.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Проект.Описание Set end)

                // *** End programmer edit section *** (Проект.Описание Set end)
            }
        }
        
        /// <summary>
        /// Обязанности.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Обязанности CustomAttributes)

        // *** End programmer edit section *** (Проект.Обязанности CustomAttributes)
        [StrLen(255)]
        public virtual string Обязанности
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Обязанности Get start)

                // *** End programmer edit section *** (Проект.Обязанности Get start)
                string result = this.fОбязанности;
                // *** Start programmer edit section *** (Проект.Обязанности Get end)

                // *** End programmer edit section *** (Проект.Обязанности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Обязанности Set start)

                // *** End programmer edit section *** (Проект.Обязанности Set start)
                this.fОбязанности = value;
                // *** Start programmer edit section *** (Проект.Обязанности Set end)

                // *** End programmer edit section *** (Проект.Обязанности Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Проект.Стоимость CustomAttributes)
        [StrLen(255)]
        public virtual string Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Стоимость Get start)

                // *** End programmer edit section *** (Проект.Стоимость Get start)
                string result = this.fСтоимость;
                // *** Start programmer edit section *** (Проект.Стоимость Get end)

                // *** End programmer edit section *** (Проект.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Стоимость Set start)

                // *** End programmer edit section *** (Проект.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Проект.Стоимость Set end)

                // *** End programmer edit section *** (Проект.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// СрокНачала.
        /// </summary>
        // *** Start programmer edit section *** (Проект.СрокНачала CustomAttributes)

        // *** End programmer edit section *** (Проект.СрокНачала CustomAttributes)
        public virtual System.DateTime СрокНачала
        {
            get
            {
                // *** Start programmer edit section *** (Проект.СрокНачала Get start)

                // *** End programmer edit section *** (Проект.СрокНачала Get start)
                System.DateTime result = this.fСрокНачала;
                // *** Start programmer edit section *** (Проект.СрокНачала Get end)

                // *** End programmer edit section *** (Проект.СрокНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.СрокНачала Set start)

                // *** End programmer edit section *** (Проект.СрокНачала Set start)
                this.fСрокНачала = value;
                // *** Start programmer edit section *** (Проект.СрокНачала Set end)

                // *** End programmer edit section *** (Проект.СрокНачала Set end)
            }
        }
        
        /// <summary>
        /// СрокЗавершения.
        /// </summary>
        // *** Start programmer edit section *** (Проект.СрокЗавершения CustomAttributes)

        // *** End programmer edit section *** (Проект.СрокЗавершения CustomAttributes)
        public virtual System.DateTime СрокЗавершения
        {
            get
            {
                // *** Start programmer edit section *** (Проект.СрокЗавершения Get start)

                // *** End programmer edit section *** (Проект.СрокЗавершения Get start)
                System.DateTime result = this.fСрокЗавершения;
                // *** Start programmer edit section *** (Проект.СрокЗавершения Get end)

                // *** End programmer edit section *** (Проект.СрокЗавершения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.СрокЗавершения Set start)

                // *** End programmer edit section *** (Проект.СрокЗавершения Set start)
                this.fСрокЗавершения = value;
                // *** Start programmer edit section *** (Проект.СрокЗавершения Set end)

                // *** End programmer edit section *** (Проект.СрокЗавершения Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Проект.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Проект.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Проект.CreateTime Get start)

                // *** End programmer edit section *** (Проект.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Проект.CreateTime Get end)

                // *** End programmer edit section *** (Проект.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.CreateTime Set start)

                // *** End programmer edit section *** (Проект.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Проект.CreateTime Set end)

                // *** End programmer edit section *** (Проект.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Creator CustomAttributes)

        // *** End programmer edit section *** (Проект.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Creator Get start)

                // *** End programmer edit section *** (Проект.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Проект.Creator Get end)

                // *** End programmer edit section *** (Проект.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Creator Set start)

                // *** End programmer edit section *** (Проект.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Проект.Creator Set end)

                // *** End programmer edit section *** (Проект.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Проект.EditTime CustomAttributes)

        // *** End programmer edit section *** (Проект.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Проект.EditTime Get start)

                // *** End programmer edit section *** (Проект.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Проект.EditTime Get end)

                // *** End programmer edit section *** (Проект.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.EditTime Set start)

                // *** End programmer edit section *** (Проект.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Проект.EditTime Set end)

                // *** End programmer edit section *** (Проект.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Editor CustomAttributes)

        // *** End programmer edit section *** (Проект.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Editor Get start)

                // *** End programmer edit section *** (Проект.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Проект.Editor Get end)

                // *** End programmer edit section *** (Проект.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Editor Set start)

                // *** End programmer edit section *** (Проект.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Проект.Editor Set end)

                // *** End programmer edit section *** (Проект.Editor Set end)
            }
        }
        
        /// <summary>
        /// Проект.
        /// </summary>
        // *** Start programmer edit section *** (Проект.Руководитель CustomAttributes)

        // *** End programmer edit section *** (Проект.Руководитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Руководитель"})]
        public virtual IIS.Product_26934.Сотрудник Руководитель
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Руководитель Get start)

                // *** End programmer edit section *** (Проект.Руководитель Get start)
                IIS.Product_26934.Сотрудник result = this.fРуководитель;
                // *** Start programmer edit section *** (Проект.Руководитель Get end)

                // *** End programmer edit section *** (Проект.Руководитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Руководитель Set start)

                // *** End programmer edit section *** (Проект.Руководитель Set start)
                this.fРуководитель = value;
                // *** Start programmer edit section *** (Проект.Руководитель Set end)

                // *** End programmer edit section *** (Проект.Руководитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Product_26934.Проект));
                }
            }
            
            /// <summary>
            /// "v3_ПроектE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v3_ПроектE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v3_ПроектE", typeof(IIS.Product_26934.Проект));
                }
            }
            
            /// <summary>
            /// "v3_ПроектL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v3_ПроектL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v3_ПроектL", typeof(IIS.Product_26934.Проект));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
