//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_26934
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список аттестаций.
    /// </summary>
    // *** Start programmer edit section *** (СписокАттестаций CustomAttributes)

    // *** End programmer edit section *** (СписокАттестаций CustomAttributes)
    [AutoAltered()]
    [Caption("Список аттестаций")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("v0.5_СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("v2_СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("v3_СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("v4_СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("v5_СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    [View("СписокАттестацийE", new string[] {
            "Название as \'Название\'",
            "ДатаПроведения as \'Дата проведения\'"})]
    public class СписокАттестаций : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fНазвание;
        
        private System.DateTime fДатаПроведения;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.Product_26934.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (СписокАттестаций CustomMembers)

        // *** End programmer edit section *** (СписокАттестаций CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.Название CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.Название Get start)

                // *** End programmer edit section *** (СписокАттестаций.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (СписокАттестаций.Название Get end)

                // *** End programmer edit section *** (СписокАттестаций.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.Название Set start)

                // *** End programmer edit section *** (СписокАттестаций.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (СписокАттестаций.Название Set end)

                // *** End programmer edit section *** (СписокАттестаций.Название Set end)
            }
        }
        
        /// <summary>
        /// ДатаПроведения.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.ДатаПроведения CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.ДатаПроведения CustomAttributes)
        public virtual System.DateTime ДатаПроведения
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.ДатаПроведения Get start)

                // *** End programmer edit section *** (СписокАттестаций.ДатаПроведения Get start)
                System.DateTime result = this.fДатаПроведения;
                // *** Start programmer edit section *** (СписокАттестаций.ДатаПроведения Get end)

                // *** End programmer edit section *** (СписокАттестаций.ДатаПроведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.ДатаПроведения Set start)

                // *** End programmer edit section *** (СписокАттестаций.ДатаПроведения Set start)
                this.fДатаПроведения = value;
                // *** Start programmer edit section *** (СписокАттестаций.ДатаПроведения Set end)

                // *** End programmer edit section *** (СписокАттестаций.ДатаПроведения Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.CreateTime CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.CreateTime Get start)

                // *** End programmer edit section *** (СписокАттестаций.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (СписокАттестаций.CreateTime Get end)

                // *** End programmer edit section *** (СписокАттестаций.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.CreateTime Set start)

                // *** End programmer edit section *** (СписокАттестаций.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (СписокАттестаций.CreateTime Set end)

                // *** End programmer edit section *** (СписокАттестаций.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.Creator CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.Creator Get start)

                // *** End programmer edit section *** (СписокАттестаций.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (СписокАттестаций.Creator Get end)

                // *** End programmer edit section *** (СписокАттестаций.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.Creator Set start)

                // *** End programmer edit section *** (СписокАттестаций.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (СписокАттестаций.Creator Set end)

                // *** End programmer edit section *** (СписокАттестаций.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.EditTime CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.EditTime Get start)

                // *** End programmer edit section *** (СписокАттестаций.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (СписокАттестаций.EditTime Get end)

                // *** End programmer edit section *** (СписокАттестаций.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.EditTime Set start)

                // *** End programmer edit section *** (СписокАттестаций.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (СписокАттестаций.EditTime Set end)

                // *** End programmer edit section *** (СписокАттестаций.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.Editor CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.Editor Get start)

                // *** End programmer edit section *** (СписокАттестаций.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (СписокАттестаций.Editor Get end)

                // *** End programmer edit section *** (СписокАттестаций.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.Editor Set start)

                // *** End programmer edit section *** (СписокАттестаций.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (СписокАттестаций.Editor Set end)

                // *** End programmer edit section *** (СписокАттестаций.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Product_26934.Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (СписокАттестаций.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (СписокАттестаций.Сотрудник CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        public virtual IIS.Product_26934.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (СписокАттестаций.Сотрудник Get start)

                // *** End programmer edit section *** (СписокАттестаций.Сотрудник Get start)
                IIS.Product_26934.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (СписокАттестаций.Сотрудник Get end)

                // *** End programmer edit section *** (СписокАттестаций.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокАттестаций.Сотрудник Set start)

                // *** End programmer edit section *** (СписокАттестаций.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (СписокАттестаций.Сотрудник Set end)

                // *** End programmer edit section *** (СписокАттестаций.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "v0.5_СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v05_СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v0.5_СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "v2_СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v2_СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v2_СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "v3_СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v3_СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v3_СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "v4_СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v4_СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v4_СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "v5_СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View v5_СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("v5_СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
            
            /// <summary>
            /// "СписокАттестацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокАттестацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокАттестацийE", typeof(IIS.Product_26934.СписокАттестаций));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of СписокАттестаций.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСписокАттестаций CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСписокАттестаций CustomAttributes)
    public class DetailArrayOfСписокАттестаций : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Product_26934.DetailArrayOfСписокАттестаций members)

        // *** End programmer edit section *** (IIS.Product_26934.DetailArrayOfСписокАттестаций members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СписокАттестаций by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СписокАттестаций.
        /// </summary>
        public DetailArrayOfСписокАттестаций(IIS.Product_26934.Сотрудник fСотрудник) : 
                base(typeof(СписокАттестаций), ((ICSSoft.STORMNET.DataObject)(fСотрудник)))
        {
        }
        
        public IIS.Product_26934.СписокАттестаций this[int index]
        {
            get
            {
                return ((IIS.Product_26934.СписокАттестаций)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Product_26934.СписокАттестаций dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
