//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_26934
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using ICSSoft.STORMNET.Business;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// РабочийПериодБС.
    /// </summary>
    // *** Start programmer edit section *** (РабочийПериодБС CustomAttributes)

    // *** End programmer edit section *** (РабочийПериодБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class РабочийПериодБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (РабочийПериодБС CustomMembers)

        // *** End programmer edit section *** (РабочийПериодБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateРабочийПериод CustomAttributes)

        // *** End programmer edit section *** (OnUpdateРабочийПериод CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateРабочийПериод(IIS.Product_26934.РабочийПериод UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateРабочийПериод)
            DateTime dt;
            if (UpdatedObject.ДатаУвольнения != null )
            {
                if (UpdatedObject.ДатаПриёма > UpdatedObject.ДатаУвольнения.Value) throw new Exception("Дата увольнения меньше даты приёма");
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateРабочийПериод)
        }
    }
}
