//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_26934
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)

    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using ICSSoft.STORMNET.Business;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник БС.
    /// </summary>
    // *** Start programmer edit section *** (СотрудникБС CustomAttributes)

    // *** End programmer edit section *** (СотрудникБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СотрудникБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (СотрудникБС CustomMembers)

        // *** End programmer edit section *** (СотрудникБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateСотрудник CustomAttributes)

        // *** End programmer edit section *** (OnUpdateСотрудник CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateСотрудник(IIS.Product_26934.Сотрудник UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateСотрудник)

            var ds = (SQLDataService)DataServiceProvider.DataService;
            var кредитныеКарты = ds.Query<Сотрудник>(Сотрудник.Views.СотрудникE)
                                 .Count(k => k.Паспорт == UpdatedObject.Паспорт && k.__PrimaryKey != UpdatedObject.__PrimaryKey );
            if (кредитныеКарты != 0) throw new Exception("Такой паспорт уже существует в системе");


            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateСотрудник)
        }
    }
}
